
server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail
    password: yourpassword(from app password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

